name: Pansensory Interactive
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#302b2f'
    - '#62615f'
    - '#0089c7'
    - '#005789'
  brandStrength: 0.12906531267799437
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
